### PR TITLE
Readme patch

### PR DESCRIPTION
**Pull request by BoxResin**
Thank you

### CODE REVIEW

**Comment by ParkSangGwon** [comment]
This library can use at jcenter() without jitpack

**Comment by BoxResin** [comment]
But I can't use the recent library(v1.0.12) with jcenter().

What about specifing two ways to setup the library in gradle?

**Comment by SpotVL** [comment]
use 

`    compile 'com.github.ParkSangGwon:TedPermission:v1.0.12'`

**Comment by ParkSangGwon** [comment]
@BoxResin 
Did you check recent Readme?
```javascript
dependencies {
    compile 'gun0912.ted:tedpermission:1.0.3'
}
```

**Comment by BoxResin** [comment]
Yes, I did. It works well but I want to use 1.0.12 version.

**Comment by ParkSangGwon** [comment]
@BoxResin 
1.0.3 version(at jcenter()) is higher than 1.0.12(at jitpack)

**Comment by BoxResin** [comment]
@ParkSangGwon 
I fixed `README.md` file. Please review it again :)

**Comment by BongJaeChoi** [comment]
usuful -> useful :)

**Comment by ParkSangGwon** [comment]
If you want merge your PR, please solve conflict

**Comment by BoxResin** [comment]
@ParkSangGwon I did it. Please review again!

**Comment by BoxResin** [comment]
Thank you!

2017년 8월 20일 (일) 오후 11:16, Ted Park <notifications@github.com>님이 작성:

**Pull request merged**
